development:
  adapter: postgresql
  encoding: unicode
  database: blog_development
  pool: 5
  username: postgres
  password:
  min_messages: WARNING

test:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  pool: 5
  username: postgres
  password:
